const productListData = [
  {
    id: 0,
    image: "https://www.pngmart.com/files/22/Mi-PNG-HD-Isolated.png",
    title: "Vivo V15 Pro (2020)",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 12_221,
    category: "Mobile",
    isCart: false,
  },
  {
    id: 1,
    image:
      "https://www.pngmart.com/files/6/Washing-Machine-PNG-Transparent-HD-Photo.png",
    title: "Samsung Washing Machine (2023)",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    price: 33_250,
    quantity: 0,
    category: "Washing Machine",
    isCart: false,
  },
  {
    id: 2,
    image: "https://www.pngmart.com/files/6/Mobile-Earphone-PNG-HD.png",
    title: "Mi earphones",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 340,
    isCart: false,
  },
  {
    id: 3,
    image: "https://www.pngmart.com/files/22/Mi-PNG-Isolated-Photo.png",
    title: "Boat Ultrasonic Smartwatch",
    description:
      "Best watch in the market to deal with sheer pace and cope up witht the growing world. `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics",
    price: 22_350,
    quantity: 0,
    isCart: false,
  },
  {
    id: 4,
    image: "https://www.pngmart.com/files/22/Mi-Download-PNG-Image.png",
    title: "Philips Trimmer",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 4_210,
    isCart: false,
  },
  {
    id: 5,
    image: "https://www.pngmart.com/files/22/Microwave-PNG-Picture.png",
    title: "Samsung Microwve (2021)",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 10_340,
    isCart: false,
  },
  {
    id: 6,
    image: "https://www.pngmart.com/files/22/Mi-PNG-Photo.png",
    title: "Xiaomi 11i (2022)",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 17_000,
    category: "Mobile",
    isCart: false,
  },
  {
    id: 7,
    image: "https://www.pngmart.com/files/22/Mi-PNG-File.png",
    title: "Mi Powerbank",
    description: `Processor & OS: 12th Gen Intel Core Processor i7-1260P (12 Cores: 4P + 8E, P: 2.1 up to 4.7 GHz / E: 1.5 up to 3.4 GHz), L3 Cache 18MB / Window 11;Memory: 16 GB LPDDR5 (Dual Channel, 5200MHz)/ Storage: 512 GB SSD M.2(2280) Dual SSD slots / Graphic: Intel Iris Xe Graphics`,
    quantity: 0,
    price: 1340,
    isCart: false,
  },
];

export default productListData;
